/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "OTACommProtocolModule"
 * 	found in "../BronComm.asn"
 */

#ifndef	_MessageError_H_
#define	_MessageError_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageError */
typedef struct MessageError {
	INTEGER_t	 error;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageError;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageError_H_ */
#include <asn_internal.h>
