/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "OTACommProtocolModule"
 * 	found in "../BronComm.asn"
 */

#ifndef	_MessageSetParameter_H_
#define	_MessageSetParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ParamValue.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageSetParameter */
typedef struct MessageSetParameter {
	ParamValue_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageSetParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageSetParameter;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageSetParameter_H_ */
#include <asn_internal.h>
