/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "OTACommProtocolModule"
 * 	found in "../BronComm.asn"
 */

#ifndef	_ParamValue_H_
#define	_ParamValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <INTEGER.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParamValue_PR {
	ParamValue_PR_NOTHING,	/* No components present */
	ParamValue_PR_data,
	ParamValue_PR_int
} ParamValue_PR;

/* ParamValue */
typedef struct ParamValue {
	ParamValue_PR present;
	union ParamValue_u {
		OCTET_STRING_t	 data;
		INTEGER_t	 Int;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParamValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParamValue;

#ifdef __cplusplus
}
#endif

#endif	/* _ParamValue_H_ */
#include <asn_internal.h>
