/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "OTACommProtocolModule"
 * 	found in "../BronComm.asn"
 */

#include "ParamValue.h"

static asn_TYPE_member_t asn_MBR_ParamValue_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ParamValue, choice.data),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ParamValue, choice.Int),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"int"
		},
};
static asn_TYPE_tag2member_t asn_MAP_ParamValue_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* int at 39 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 0, 0, 0 } /* data at 37 */
};
static asn_CHOICE_specifics_t asn_SPC_ParamValue_specs_1 = {
	sizeof(struct ParamValue),
	offsetof(struct ParamValue, _asn_ctx),
	offsetof(struct ParamValue, present),
	sizeof(((struct ParamValue *)0)->present),
	asn_MAP_ParamValue_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ParamValue = {
	"ParamValue",
	"ParamValue",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_ParamValue_1,
	2,	/* Elements count */
	&asn_SPC_ParamValue_specs_1	/* Additional specs */
};

