/*****************************************************************************
* Model: co2013.qm
* File:  generated/evt_middleware_time.h
*
* This code has been generated by QM tool (see state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*****************************************************************************/
/*${Events::generated::evt_middleware_time.h} ..............................*/
#ifndef __EVT_MIDDLEWARE_TIME_H__
#define __EVT_MIDDLEWARE_TIME_H__

#include "globals.h"

typedef void(*FunctionPtr)(void);

/*${Events::Middleware_TimeEvt} ............................................*/
typedef struct {
/* protected: */
    QTimeEvt super;

/* public: */
    FunctionPtr m_pCallback;
    void* m_pContext;
} Middleware_TimeEvt;


#endif /* __EVT_MIDDLEWARE_TIME_H__ */
